project/atelier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import (home_view, explore_view, dance_view, photography_view, music_view, filming_view, art_view,
                    food_view, illustration_view, poetry_view, craft_view, fashion_view, index_view,
                    about_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index-view'),
    path('home/', home_view, name='home-view'),
    path('explore/', explore_view, name='explore-view'),
    path('about/', about_view, name='about-view'),
    path('photography/', photography_view, name='photography-view'),
    path('dance/', dance_view, name='dance-view'),
    path('music/', music_view, name='music-view'),
    path('filming/', filming_view, name='filming-view'),
    path('art/', art_view, name='art-view'),
    path('illustration/', illustration_view, name='illustration-view'),
    path('food/', food_view, name='food-view'),
    path('poetry/', poetry_view, name='poetry-view'),
    path('craft/', craft_view, name='craft-view'),
    path('fashion/', fashion_view, name='fashion-view'),
    
    
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/blog/urls.py
from django.urls import path
from .views import shop_views

app_name = 'blog'

urlpatterns = [

    path('', shop_views, name='shop-view')
]

project/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

project/profiles/urls.py
from django.urls import path
from .views import ( 
    my_profile_view, 
    invites_received_view, 
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileDetailView,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

project/templates/main/about.html
{% extends "base.html" %}
{% block title %} Team {% endblock %}


{% block head %}
{% load static %}
<link href="{% static 'about.css' %}" rel="stylesheet" type="text/css">
{% endblock head %}




{% block content %}
<!-- For demo purpose -->
<div class="ui center aligned container">
    <div class="row text-center text-white">
        <div class="col-lg-8 p-3 p-md-5 mx-auto">
            <h1 class="display-4"><b>OUR CREATIVE TEAM</b></h1>
            <p class="lead mb-0">“Talent wins games, but teamwork and intelligence win championships.”</p>
        </div>
    </div>
</div><!-- End -->

<br>
<br>
<div class="ui four column grid">
    <div class="row">

        <!-- Team item -->
        <div class=" column  " >
            <div class="column"><img class="ui small circular image" src="{% static 'anjali.png'%}" alt="" width="100" height="100" ">
                <h5 class="">Anjali Bhatt</h5>
                <span class="small text-uppercase text-muted">CEO - Founder</span>

                <div class="ui circular labels row" >
                    <a style="color:black" href="#"> <i class="facebook icon"></i></a>
                    <a style="color:black" href="#"> <i class="twitter icon"></i></a>
                    <a style="color:black" href="#"> <i class="instagram icon"></i></a>
                    <a style="color:black" href="#"><i class="linkedin icon"></i></a>
                </div>
            </div>
        </div><!-- End -->

        <!-- Team item -->
        <div class="column">
            <div class="column"><img class="ui small circular image" src="{% static 'shivani.jpg' %}" alt="" width="100"  >
                <h5 class="mb-0">SHIVANI THOMBARE</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                <div class="row">
                    <a style="color:black" href="#"> <i class="facebook icon"></i></a>
                   <a style="color:black" href="#"> <i class="twitter icon"></i></a>
                   <a style="color:black" href="#"> <i class="instagram icon"></i></a>
                    <a style="color:black" href="#"><i class="linkedin icon"></i></a>
                </div>
            </div>
        </div><!-- End -->

        <!-- Team item -->
        <div class="column">
            <div class="column"><img src="{% static 'aditi.jpg' %}" alt="" width="100" class="ui small circular image" >
                <h5 class="mb-0">ADITI SHIRBATE</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                <div class="row">
                    <a style="color:black" href="#"> <i class="facebook icon"></i></a>
                   <a style="color:black" href="#"> <i class="twitter icon"></i></a>
                   <a style="color:black" href="#"> <i class="instagram icon"></i></a>
                    <a style="color:black" href="#"><i class="linkedin icon"></i></a>
                </div>
            </div>
        </div><!-- End -->

        <!-- Team item -->
        <div class="column">
            <div class="column"><img src="{% static 'viren.png' %}" alt="" width="100" class="ui small circular image">
                <h5 class="mb-0">Viren Ghuikhedkar</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                <div class="row">
                    <a style="color:black" href="#"> <i class="facebook icon"></i></a>
                   <a style="color:black" href="#"> <i class="twitter icon"></i></a>
                   <a style="color:black" href="#"> <i class="instagram icon"></i></a>
                    <a style="color:black" href="#"><i class="linkedin icon"></i></a>
                </div>
            </div>
        </div><!-- End -->
    </div>
</div>

<br>
<br>
<hr>
<br>
<br>




<!--<div class="container-fluid tm-mt-60">-->
    <div class="ui three column grid ">
        <div class="ui inverted column segment">
            <div class="ui inverted form column">
                <div class="field">
                    <label> Name</label>
                    <input placeholder="Name" type="text">
                </div>
                <div class="field">
                    <label>E-mail</label>
                    <input type="email" placeholder="joe@schmoe.com">
                </div>
                <div class="field">
                    <label>Leave your message here:</label>
                    <textarea rows="15"></textarea>
                </div>
                <div class="field">
                    <label>Message Type:</label>
                    <div class="ui selection dropdown">
                        <input type="hidden" name="message-type">
                        <i class="dropdown icon"></i>
                        <div class="default text">Message Type</div>
                        <div class="menu">
                            <div class="item" data-value="1">Complaint</div>
                            <div class="item" data-value="0">Query</div>
                        </div>
                    </div>
                </div>
                <div class="ui submit button">Submit</div>
            </div>
        </div>
        <div class="ui inverted column " style="padding-top:360px;">
            <div class="tm-address-col">
                <h2 class="tm-text-primary mb-5">Our Address</h2>
                <p class="tm-mb-50">Railway station, Solapur - Pune Hwy, near Bharat Petrol Pump, Loni Kalbhor, Maharashtra 412201</p>
                <p class="tm-mb-50">Loni Kalbhor, Maharashtra 412201</p>
                <address class="tm-text-gray tm-mb-50">
                    Railway station, Solapur - Pune Hwy, near Bharat Petrol Pump,<br>
                    Loni Kalbhor, Maharashtra 412201
                </address>
                <ul class="tm-contacts">
                    <li>
                        <a href="#" class="tm-text-gray">
                            <i class="fas fa-envelope"></i>
                            Email: atelier04@gmail.com
                        </a>
                    </li>
                    <li>
                        <a href="#" class="tm-text-gray">
                            <i class="fas fa-phone"></i>
                            Tel: 010-020-0340
                        </a>
                    </li>
                    <li>
                        <a href="#" class="tm-text-gray">
                            <i class="fas fa-globe"></i>
                            URL: www.atelier.com
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="ui inverted column segment">
            <h2 class="tm-text-primary mb-5">Our Location</h2>
            <!-- Map -->
            <div class="mapouter mb-4">
                <div class="gmap-canvas">
                    <iframe width="100%" height="500" id="gmap-canvas"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30250.335124089146!2d73.76691905!3d18.605936500000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2e805e62101f9%3A0x20beded1f9debf8d!2sMIT%20ADT%20University!5e0!3m2!1sen!2sin!4v1604565657114!5m2!1sen!2sin"
                            frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                </div>
            </div>
        </div>
    </div>
<!--</div>-->
<br>
<br>
<hr>
<br>
<br>
<footer class="tm-bg-gray pt-5 pb-3 tm-text-gray tm-footer">
    <div class="container-fluid tm-container-small">
        <div class="ui two column grid">
            <div class="col-lg-6 col-md-12 col-12 px-5 mb-5">
                <h3 class="tm-text-primary mb-4 tm-footer-title">About Bloomverse</h3>
                <p>A website that is aming to :<br>
                    1)Nearly, 20 million tons of floral waste are generated every day - We aim to reduce flower waste <br>
                    2)More than 15 billion trees are lost annually to deforestation. - Our objective is to increase the rate of tree plantation <br>
                    3)Promote eco-friendly products

                </p>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 px-5 mb-5">
                <h3 class="tm-text-primary mb-4 tm-footer-title">Our Links</h3>
                <ul class="tm-footer-links pl-0">
                    <li><a href="#">Advertise</a></li>
                    <li><a href="#">Support</a></li>
                    <li><a href="#">Our Company</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-7 col-12 px-5 mb-3">
                ©Copyright 2020. All rights reserved.
            </div>
        </div>
    </div>
</footer>

{% endblock %}

project/templates/main/art.html
{% extends 'base.html' %}

{% block title %}ART{% endblock title %}
{% load static %}


{% block head %}


{% endblock head %}




{% block content %}


<div class="ui three column grid">

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/art/1.jpg' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username1</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/art/2.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/art/3.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/art/4.jpg' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/art/5.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/art/6.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>


{% endblock content %}

project/templates/main/craft.html
{% extends 'base.html' %}

{% block title %}Photography{% endblock title %}
{% load static %}


{% block head %}

    {% comment %} <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css"> {% endcomment %}

{% endblock head %}




{% block content %}


<div class="ui three column grid">

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/craft/craft1.jpg' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/craft/craft2.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/craft/craft3.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/craft/craft4.png' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/craft/craft5.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/craft/craft6.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>



{% endblock content %}

project/templates/main/dance.html
{% extends "base.html" %}
{% block title %} Explore-Dance {% endblock %}


{% block head %}
{% load static %}
    {% comment %} <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}

    <style>
div.ui.col {
    border-style:solid;
    border-width:10px;
}
    </style>

{% endblock %}




{% block content %}

<main>

  <section class="ui py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">

        <h1 class="fw-light">DANCE</h1>
        <p class="lead text-muted">"When you dance, you can enjoy the luxury of being you." -Paulo Coelho </p>
        <p>
          {% comment %} <a href="#" class="btn btn-primary my-2">Add Your Video</a> {% endcomment %}

        </p>
      </div>
    </div>
  </section>

  
      <div class="ui three colunm centered grid" style="padding:20px; ">
        <div class="ui col">
          <div class="card shadow-sm">

            <video width="320" height="240" controls>
            <source src="{% static 'explore/1.mp4' %}">
              </video>



            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username1</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">

            <video width="320" height="240" controls>
              <source src="{% static 'explore/2.mp4' %}">
                </video>

            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username2</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/3.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username3</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>

        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/5.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username4</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/6.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username5</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video  width="320" height="240" controls>
              <source src="{% static 'explore/7.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username6</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>

        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/8.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username7</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/9.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username8</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="ui col" style="padding-bottom:20px;">
          <div class="card shadow-sm">
            <video width="320" height="240" controls>
              <source src="{% static 'explore/4.mp4' %}">
                </video>
            <div class="card-body">
              <button type="button" class="ui gray button" style="margin-right:200px;">Username9</button>
              <p class="card-text">This is the sample video.</p>
              <div class="d-flex justify-content-between align-items-center">
                {% comment %} <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                </div> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
      </div>
    
  

</main>
{% endblock %}

{% block scripts %}
    {% endblock scripts %}

project/templates/main/fashion.html
{% extends 'base.html' %}

{% block title %}Photography{% endblock title %}
{% load static %}


{% block head %}


{% endblock head %}




{% block content %}


<div class="ui three column grid">

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/fashion/fashion1.jpg' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/fashion/fashion2.png' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/fashion/fashion3.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/fashion/fashion4.jpg' %}">
    
    <div class="content">
      <a class="header"  href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription</a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
      <img class="ui large  image" src="{% static 'explore/fashion/fashion5.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a class="description" style="color:black;">Discription
          
        </a>
      </div>
    </div> 
    </div>
  </div>

  <div class="column">
    <div class="ui segment">
     <img class="ui large image" src="{% static 'explore/fashion/fashion6.jpg' %}">
    
    <div class="content">
      <a class="header" href="#"><b>Username</b></a>
      <div class="meta">
        <a style="color:black;" class="description">Discription
          
        </a>
      </div>
    </div>
   </div>  
  </div>



{% endblock content %}

project/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'explore-view' as path_to_explore %}
{% url 'about-view' as path_to_about %}
{% url 'blog:shop-view' as path_to_shop %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}


<div class="ui fixed inverted menu nav mb-7 navbar-dark bg-dark ">
  <div class="ui container">
      {% if request.user.is_authenticated %}
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Bloomverse</h3>
    </a>
      {% else %}
      <a href="{{path_to_about}}" class="{% if request.path == path_to_about %}active{% endif %} item">
        <h3>Bloomverse</h3>
    </a>
      {% endif %}

    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    <!--<a href="{{path_to_home}}" class="ui item">
        Home
    </a>-->
    <!--<a href="{{path_to_explore}}" class="ui item">
        Explore
    </a>-->
    <a href="{{path_to_shop}}" class="ui item">
    Shop
    </a>
    {% endif %}



    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Tie-ups
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
<!--                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">-->
<!--                        Send Invites-->
<!--                    </a>-->
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Sign In
            </a>
        <a href="{% url 'account_signup' %}" class="ui item">
                Sign Up
            </a>
        {% endif %}
    </div>
  </div>
</div>